### ISSUE TITLE
Fails when browsersync option ui:false is set

### ISSUE THREAD

**Issue by EmbeddedMike** [itgalaxy/browser-sync-dev-hot-webpack-plugin#1]
When Browsersync is configured with 

`ui: false`

the server crashes (stack trace at the bottom). I traced the problem to these lines of code in `BrowserSyncDevHotWebpackPlugin.js`

```
        proxyReq.setHeader('X-Browser-Sync-URL-UI', browserSyncURLUI);
        proxyReq.setHeader('X-Browser-Sync-URL-UI-External', browserSyncURLUIExternal);
```

I've tested it by commenting out the lines and it works. The fix would be to guard them with something like:
```
       if (browserSyncURLUI && browserSyncURLUIExternal ) {
          proxyReq.setHeader('X-Browser-Sync-URL-UI', browserSyncURLUI);
          proxyReq.setHeader('X-Browser-Sync-URL-UI-External', browserSyncURLUIExternal);
        }

```
It's possible to guard them separately, but I don't think that would make sense.

If you'd like me to do a pull request for you, I will do it, but given the simplicity of the change it might be easier for you to do it yourself.

Here's the stack trace:

```
   Local: http://localhost:3000
 External: http://192.168.1.17:3000
 ----------------------------------
_http_outgoing.js:354
    throw new Error('"value" required in setHeader("' + name + '", value)');
    ^
Error: "value" required in setHeader("X-Browser-Sync-URL-UI", value)
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
    at merge.all.proxy.proxyReq (/home/mwolf/tools/junk/node_modules/browser-sync-dev-hot-webpack-plugin/src/BrowserSyncDevHotWebpackPlugin.js:57:38)
    at /home/mwolf/tools/junk/node_modules/browser-sync/lib/server/proxy-server.js:129:24
    at List.__iterate (/home/mwolf/tools/junk/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/home/mwolf/tools/junk/node_modules/immutable/dist/immutable.js:4383:19)
    at ProxyServer.<anonymous> (/home/mwolf/tools/junk/node_modules/browser-sync/lib/server/proxy-server.js:127:17)
    at ProxyServer.emit (/home/mwolf/tools/junk/node_modules/eventemitter3/index.js:119:35)
    at ClientRequest.<anonymous> (/home/mwolf/tools/junk/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:117:27)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at tickOnSocket (_http_client.js:574:7)
    at onSocketNT (_http_client.js:586:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by evilebottnawi** [comment]
@EmbeddedMike thanks, do PR, i don't have time now :sob:
